### ISSUE TITLE
Missing `set` attribute

### ISSUE THREAD

**Issue by demurgos** [types/npm-minimatch#1]
Hi,
The current definitions are missing the [the `set` property](https://github.com/isaacs/minimatch#properties) of the `Minimatch` class.

It should be typed as:

```typescript
/**
A 2-dimensional array of regexp or string expressions. Each row in the array corresponds
to a brace-expanded pattern. Each item in the row corresponds to a single path-part. 
*/
set: (string | RegExp)[][]
```

**Comment by blakeembrey** [comment]
Sorry for the delay, just got around to updating the project 👍
